using Pontis.Game;
using Pontis.Interfaces;

namespace Pontis.CardDatabases;

public class NoJacks: IDeckDefinition
{
    
    public NoJacks()
    {
        Cards = _cards;
    }
    public IEnumerable<ICard> Cards { get; }
    
    private readonly IEnumerable<ICard> _cards = new List<ICard>()
    {
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ace, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 11 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Two, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 2 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Three, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 3 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Four, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 4 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Five, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 5 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Six, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 6 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Seven, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 7 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Eight, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 8 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Nine, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 9 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ten, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Jack, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Queen, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.King, 
            suit: Constants.Suits.Clubs, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ace, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 11 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Two, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 2 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Three, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 3 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Four, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 4 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Five, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 5 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Six, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 6 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Seven, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 7 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Eight, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 8 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Nine, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 9 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ten, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Jack, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Queen, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.King, 
            suit: Constants.Suits.Diamond, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),

        new PontisCard( isJoker: false , kind: Constants.Kinds.Ace, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 11 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Two, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 2 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Three, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 3 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Four, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 4 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Five, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 5 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Six, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 6 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Seven, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 7 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Eight, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 8 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Nine, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 9 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ten, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Jack, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Queen, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.King, 
            suit: Constants.Suits.Hearts, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),

        new PontisCard( isJoker: false , kind: Constants.Kinds.Ace, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 11 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Two, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 2 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Three, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 3 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Four, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 4 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Five, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 5 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Six, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 6 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Seven, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 7 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Eight, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 8 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Nine, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 9 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Ten, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Jack, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.Queen, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
        new PontisCard( isJoker: false , kind: Constants.Kinds.King, 
            suit: Constants.Suits.Spades, open: false, meld: null,
            owner: Constants.Owners.Deck, score: 10 ),
    };

}